
    - name: Install vim-jsx
      git: repo=https://github.com/mxw/vim-jsx.git dest=~/.vim/bundle/vim-jsx
      tags:
      - react
      - development

    - name: Enable JSX in JS files
      lineinfile: dest=~/.vimrc line="let g:jsx_ext_required = 0"
      tags:
      - react
      - development

    - name: Install global NPM packages
      npm: name={{ item.name }} version={{ item.version }} global=yes
      become: yes
      with_items:
      - {name: create-react-app, version: 0.3.0}
      tags:
      - react
      - development
